spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

logging.level:
  org.hibernate.orm.jdbc.bind: trace
  org.springframework.cache: TRACE